version: 2.1

orbs:
   android: circleci/android@3.0.2

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/android:2025.01
    steps:
      - checkout
      - android/restore_gradle_cache
      - run:
          name: Chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Install dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Build project
          command: ./gradlew clean assemble
      - android/save_gradle_cache

  unit tests:
    working_directory: ~/project
    docker:
      - image: cimg/android:2025.01
    steps:
      - checkout
      - android/restore_gradle_cache
      - run:
          name: Chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Run Local UnitTests
          command: |
            ./gradlew testDebugUnitTest
      - android/save_gradle_cache
      - store_test_results:
          path: app/build/reports/test/testDebugUnitTest
      - store_artifacts:
          path: app/build/reports/test/testDebugUnitTest


  instrumented_test:
    executor:
      name: android/android_machine
      resource_class: large
      tag: 2024.01.1
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - android/change_java_version:
          java_version: 17
      - run:
          name: Chmod permissions
          command: chmod +x ./gradlew
      - android/create_avd:
          avd_name: myAvd
          install: true
          system_image: system-images;android-29;default;x86_64
      - android/start_emulator:
          avd_name: myAvd
          no_window: true
          restore_gradle_cache_prefix: v1a
      - android/run_tests
      - store_test_results:
          path: app/build/outputs/androidTest-results
      - store_artifacts:
          path: app/build/outputs/androidTest-results
      - android/save_gradle_cache:
          cache_prefix: v1a

workflows:
  build_and_testing:
    jobs:
      - build
      - instrumented_test:
          requires:
            - build
      - unit tests:
          requires:
            - build
