version: 2.1

orbs:
  android: circleci/android@2.3.0

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/android:2024.11
    steps:
      - checkout
      - android/restore-gradle-cache
      - run:
          name: Chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Install dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Build project
          command: ./gradlew clean assemble
      - android/save-gradle-cache

  unit tests:
    working_directory: ~/project
    docker:
      - image: cimg/android:2024.11
    steps:
      - checkout
      - android/restore-gradle-cache
      - run:
          name: Chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Run Local UnitTests
          command: |
            ./gradlew clean test
      - android/save-gradle-cache
      - store_test_results:
          path: app\build\test-results


  instrumented_test:
    executor:
      name: android/android_machine
      resource_class: large
      tag: default
    steps:
      - checkout
      - android/create_avd:
          avd_name: myavd
          install: true
          system_image: system-images;android-31;default;x86_64
      - android/start_emulator:
          avd_name: myavd
          no_window: true
          restore_gradle_cache_prefix: v1a
      - android/run_tests
      - android/save_gradle_cache:
          cache_prefix: v1a
      - store_test_results:
          path: app\build\outputs\androidTest-results

workflows:
  build_and_testing:
    jobs:
      - build
      - instrumented_test:
          requires:
            - build
      - unit tests:
          requires:
            - build
